services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./build/main.Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - algo-network

networks:
  algo-network:
    name: algo-network
    driver: bridge
